name: 'Required JIRA Approvals'
description: 'Check labels for convention ending with -required/-approved'
inputs:
  commit_message:
    description: The commit message that contains the JIRA story.
    required: true
  jira_user:
    description: The email of the jira user.
    required: true
  jira_token:
    description: The API token associated to the user.
    required: true
  jira_url:
    description: The base URL for jira
    required: true
  default_labels:
    description: Assumed required status
    required: true
    default: 'QA Verified'
  required_suffix:
    description: Append this to the end of a label to mark it required
    required: false
    default: 'required'
  approved_suffix:
    description: Append this to the end of a label to mark it approved
    required: false
    default: 'approved'
runs:
  using: 'node12'
  main: 'dist/index.js'
